#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robot-cdr2022','console_scripts','hal'
__requires__ = 'robot-cdr2022'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robot-cdr2022', 'console_scripts', 'hal')()
    )
